version: '3.9'
services:
    nodejs:
       build:
         context: ./nodejs
         dockerfile: Dockerfile
       profiles: ["dev", "staging"]
       ports:
         - "9004:3000"
    
    laravel:
       build:
         context: ./laravel
         dockerfile: Dockerfile
       profiles: ["staging", "production"]
    

    database:
       image: mysql
       env_file:
          - .env
       volumes:
          - ./custom:/etc/mysql/conf.d
       profiles: ["staging", "production"]
