stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: my-node-app
  CONTAINER_NAME: my-node-container

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME .

deploy_to_local:
  stage: deploy
  script:
    - docker run -d --name $CONTAINER_NAME -p 3000:3000 $DOCKER_IMAGE_NAME

